### ISSUE TITLE
Change required following API changes in Bagnon 8.2.18

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Jaliborc/Bagnon-Scrap#1]
Thank you for this great addon. I took almost all of its code in order to integrate with Bagnon for my own addon, so now is payback time.

In this commit https://github.com/tullamods/Bagnon/commit/66ef9412fa7d3f6eb9ec91930316ec3818213abd#diff-05bb8930f4d1c44c1b5b8d9747e8eb5fL8 the API changed from ItemSlot to Item and so it breaks addon relying on it. For GreyHandling I've done it this way: https://github.com/Pierre-Sassoulas/grey-handling/commit/b082452902363fe4ff87f848a5125b87b1ddcf65

I hope this help.

**Comment by Jaliborc** [comment]
I know, I know. I'm the author of Bagnon AND Scrap :D
Just Scrap is also rewritten internally, getting all Scrap plugins ready at once to release everything in one go.

But thanks for the help!

**Comment by Pierre-Sassoulas** [comment]
Haha! Well, everything I do depends on your work then. I hope `Scrap:IsJunk(itemid, bagID, bagSlot)` will stay stable :p

Closing the ticket, thank you for your answer :)

**Comment by Jaliborc** [comment]
Scrap ain't changing any of its main API, so you should be good to go!
Only it's load on demand "Merchant" API its moving around.

**Comment by Jaliborc** [comment]
See the "experimental" branch if you wanna look ahead. It's pretty much final already.
